api:
  -
    name : "cryptocompare"
    url : "https://min-api.cryptocompare.com/data/v2/"
    apikey : "Apikey *****"
    param :
        range : "histominute"
        fsym: "BTC"
        tsym: "USD"
        limit: "10"